version: 0.0
os: linux
files:
  - source: /
    destination: /hello-react 
hooks:
  ApplicationStop:
    - location: /hello-react/scripts/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /hello-react/scripts/start.sh
      timeout: 300
      runas: root